export const podcastData = [
  {
    guest: "Rushi",
    company: "Movement Labs",
    category: "Founder",
    image: "/logos/movement-labs.png",
  },
  {
    guest: "Eunice",
    company: "Monad",
    category: "Founder",
    image: "/logos/Monad.png",
  },
  // {
  //   guest: "Yano",
  //   company: "Blockworks",
  //   category: "Founder",
  //   image: "/logos/Blockworks.png",
  // },
  {
    guest: "Michael",
    company: "OG",
    category: "Founder",
    image: "/logos/0G-Labs.png",
  },
  {
    guest: "Prabal",
    company: "Avail",
    category: "Founder",
    image: "/logos/Prabal-Avail.png",
  },
  {
    guest: "Misha",
    company: "Symbiotic",
    category: "Founder",
    image: "/logos/Symbiotic.png",
  },
  {
    guest: "Kenny",
    company: "Manta",
    category: "Founder",
    image: "/logos/Manta-Network.png",
  },
  {
    guest: "Sandeep",
    company: "Polygon",
    category: "Founder",
    image: "/logos/Polygon.png",
  },
  {
    guest: "Kash",
    company: "Superteam",
    category: "Founder",
    image: "/logos/Kash-Superteam.png",
  },
  {
    guest: "Rob",
    company: "Dragonfly",
    category: "VC",
    image: "/logos/dragonfly.png",
  },
  {
    guest: "Shayon",
    company: "Multicoin Capital",
    category: "VC",
    image: "/logos/multicoin-capital.png",
  },
  {
    guest: "Akshat",
    company: "Maelstrom",
    category: "VC",
    image: "/logos/Maelstrom.png",
  },
  {
    guest: "Austin",
    company: "Relayer Capital",
    category: "VC",
    image: "/logos/Relayer-Capital.png",
  },
  // {
  //   guest: "Peter",
  //   company: "Fenbushi",
  //   category: "VC",
  //   image: "/logos/Fenbushi-Capital.png",
  // },
  {
    guest: "Belinda",
    company: "Sharding Capital",
    category: "VC",
    image: "/logos/Sharding-Capital.png",
  },
  {
    guest: "Sachi",
    company: "Polygon Ventures",
    category: "VC",
    image: "/logos/Polygon.png",
  },
  {
    guest: "Juliet",
    company: "New Tribe Capital",
    category: "VC",
    image: "/logos/new-tribe-capital.png",
  },
  // {
  //   guest: "Jason",
  //   company: "OKX",
  //   category: "COO",
  //   image: "/logos/OKX.png",
  // },
  {
    guest: "Mark",
    company: "Polygon Labs",
    category: "CEO",
    image: "/logos/Polygon.png",
  },
  {
    guest: "Alessia",
    company: "DWF",
    category: "Ecosystem",
    image: "/logos/DWF-Labs.png",
  },
  {
    guest: "Seraphim",
    company: "Ethena",
    category: "Growth",
    image: "/logos/Ethena-Labs.png",
  },
  // {
  //   guest: "Binji",
  //   company: "Optimism",
  //   category: "Growth",
  //   image: "/logos/Optimism.png",
  // },
  // {
  //   guest: "Saneel",
  //   company: "Ritual",
  //   category: "Growth",
  //   image: "/logos/Ritual.png",
  // },
];
